services:
  wordpress:
    image: cloud66/wordpress:4.1.0
    ports:
    - 80:80:443
    health:
      type: normal
      endpoint: "/"
      protocol: http
      timeout: 60s
      accept:
      - '200'
      - 300-399
    restart_on_deploy: false  
databases:
- mysql